# Generated by Django 4.2.10 on 2024-03-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_listaDeTarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadetareda',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listadetareda',
            name='fazer',
            field=models.BooleanField(default=True),
        ),
    ]
