# Generated by Django 4.2.10 on 2024-03-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_listaDeTarefas', '0002_listadetareda_concluido_listadetareda_fazer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadetareda',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='listadetareda',
            name='fazer',
        ),
        migrations.AddField(
            model_name='listadetareda',
            name='status',
            field=models.CharField(choices=[('fazer', 'A fazer'), ('concluido', 'Concluido')], default='fazer', max_length=30),
        ),
    ]
