# Generated by Django 4.2.10 on 2024-03-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_listaDeTarefas', '0003_remove_listadetareda_concluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadetareda',
            name='status',
            field=models.CharField(choices=[('fazer', 'A fazer'), ('concluido', 'Concluido')], max_length=30),
        ),
    ]
