# Generated by Django 4.2.10 on 2024-03-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_listaDeTarefas', '0004_alter_listadetareda_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadetareda',
            name='status',
            field=models.CharField(choices=[('fazer', 'A fazer'), ('concluido', 'Concluido')], default='fazer', max_length=30),
        ),
    ]
